[features]
seeds = false
skip-lint = false
[programs.devnet]
monthly_subscription_solana = "GySjZVLx2nSYBT6zhhpk5YsyqNhngwZa28AmXosK8bjv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Create.ts"
suscribe = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Suscribe.ts"
